### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by waghanza** [sdogruyol/kemal#126]
Hi,

I have made an app https://github.com/waghanza/forest that use `kemal`

~~~crystal
get "/:table" do |env|
~~~
when I
~~~sh
curl http://$IP/toto
~~~

I have a `404` and a
~~~crystal
Exception: Requested path: 'GET:/toto' was not found.
~~~

Does something evolves since `0.9.3` ?

**Comment by sdogruyol** [comment]
@waghanza we've update the Radix router and guess this is related to that.

**Comment by waghanza** [comment]
the problem seems not to be `kemal`
I enter me `GET` method  but only when I comment the line 
~~~crystal
db = PG.connect("...")
~~~
strange ?

**Comment by jmoriau** [comment]
Not strange at all, this is related to #97, your connect fails, which throws an exception so anything after that is not evaluated, it will jump to the `at_exit` hook, and start the server as if nothing happened, but the reality is nothing after your connect has be evaluated, so all your routes are not defined.

**Comment by waghanza** [comment]
bingo, thanks

**Comment by jmoriau** [comment]
You shouldn't close it, if all issues regarding this are closed it will never get fixed.

**Comment by waghanza** [comment]
yes, It has been fixed

it just a misunderstanding by myself

ah, yes in fact this behavior could be documented

**Comment by jmoriau** [comment]
Your issue has been worked around, but the root of this issue is not fixed yet. It shoudn't fail silently and still start the server when an exception happens.

**Comment by sdogruyol** [comment]
With version `0.11.0` `Kemal` won't run if there's an exception. Be sure to read the release notes https://github.com/sdogruyol/kemal/releases/tag/v0.11.0
