### ISSUE TITLE
Kemal suppresses runtime-errors

### ISSUE THREAD

**Issue by Thyra** [sdogruyol/kemal#97]
If you execute this short piece of code:
```crystal
require "kemal"

get "/" do
  "Hello, World!"
end

if true
  raise "This is an Error!"
end

get "/hi" do
  "Hello, World!"
end
```
the results are quite weird: There is nowhere a notice of the error (neither logs nor in the browser) and you can open `/` but if you open `/hi` in the browser window, kemal says *Kemal doesn't know this way.* 

I understand this is because `/` gets registered, then the program crashes and kemal's `at_exit` is executed, so everything after the error simply gets dropped.

Wouldn't it be better if kemal would clearly report the error and abort? I think it would make debugging much easier and a half-working webserver which doesn't know half of its supposed pages is anyway not helpful ;-).

**Comment by sdogruyol** [comment]
It's because of the `at_exit` hook. It supresses the exceptions.

**Comment by Thyra** [comment]
OK, I scanned the docs and there seems to be no way to mitigate that directly. For me and other developers of plugins for kemal I think it is quite important to have a way to report errors to the user, for example:
```crystal
require "kemal"
require "kemal-session"

# This raises an exception if the directory does not exist:
Session.config.engine = Session::FileSystemEngine.new({sessions_dir: "./sessions/"}) 

get "/" do
  #...
end

#...
```
So I created a ``Kemal.raise`` method that I can use (look at the pull request). Then instead of raising an exception directly when the directory does not exist I can call ``Kemal.raise`` and Kemal knows that there have been exceptions and react accordingly.

What do you think about this idea?

**Comment by jmoriau** [comment]
It won't stop other exceptions that weren't raised by `Kemal.raise` (exceptions from the standard library for example) from being silently ignored, it would be a half-solution.

**Comment by Thyra** [comment]
That is true, but I don't see a better way right now. It would also be possible to overwrite the original `raise` defs but I don't feel comfortable with that. Besides, this problem concerns only runtime-errors that are not encapsuled in a get/post... block, for these Kemal does provide a 500 message in the browser.
So I think most of the code that could cause this problem is using kemal plugins. And if they are properly written there shouldn't be any exceptions from the standard library.

**Comment by jmoriau** [comment]
I don't know I think the better solution would be to stop using the `at_exit` hook (I don't have a specific idea how but would be cleaner imho).

**Comment by sdogruyol** [comment]
@Thyra runtime errors are the problem like you mentioned before. 

I also agree that we need better error handling for those but i also can't find a way for now.

**Comment by f** [comment]
I think this is solved with https://github.com/sdogruyol/kemal/pull/125

**Comment by sdogruyol** [comment]
Yesh closed with #125

**Comment by jmoriau** [comment]
No it doesn't solve this, as long as the at_exit hook is used and swallows every previous exceptions this is not solved.
